### ISSUE TITLE
IntelliSense for project

### ISSUE THREAD

**Issue by Splines** [bhoov/manim-notebook#11]
Does TypeScript IntelliSense work for you in this project? For me I get: `Project Wide IntelliSense not available` and this is quite annoying as IntelliSense is really limited. I've installed the dependencies via `npm install` is there anything else to do?

**Comment by Splines** [comment]
bhoov replied to me in https://github.com/bhoov/vscode-manim/pull/7#issuecomment-2426972651:

> I have not had a problem with Intellisense for this project. Weird...

**Comment by bhoov** [comment]
In my vscode I see intellisense completion as normal, see the screenshot for your contributed `previewCode` function

<img width="851" alt="image" src="https://github.com/user-attachments/assets/738d0e81-1c8d-4aeb-81f5-4e9cfb28aff8">

I am not sure why you are getting this error. Can you try running `npm install --save-dev` to get the type files for the project?

**Comment by Splines** [comment]
I've also runned `npm install --save-dev` but it said "up to date", so it didn't do anything.

So does this work for you: write `vscode.window.`, then see the methods on the window objects? Or anything else from the `vscode` namespace?

**Comment by bhoov** [comment]
Yes, indeed my `vscode.window.` intellisense works as expected

<img width="951" alt="image" src="https://github.com/user-attachments/assets/af6afdcc-96b2-439b-8226-753f2038b731">

**Comment by Splines** [comment]
I filed a respective issue [here](https://github.com/microsoft/vscode/issues/231954).

**Comment by bhoov** [comment]
@Splines if you agree that this issue is outside the scope of this repository's code, can we close?
