### ISSUE TITLE
Rename extension to "Manim Notebook"

### ISSUE THREAD

**Issue by Splines** [bhoov/manim-notebook#13]
From [here](https://github.com/bhoov/vscode-manim/pull/7#issuecomment-2427585497):

> However (and this is worth discussion) I expect others to develop Manim extensions on VSCode and I would like this extension to focus on the interactive workflow (e.g., there is already [Manim Sideview](https://marketplace.visualstudio.com/items?itemName=Rickaym.manim-sideview) whose functionality is orthogonal to that of this project). Indeed, the name of this extension likely needs to be improved from "vscode-manim" which does not capture the emphasis on interactive development. How should we brand this package on the marketplace? This will effect what we choose for the category of each cmd in package.json

**Comment by Splines** [comment]
Some first suggestions: maybe `Interactive Manim`, at least pragmatic. But I don't like that it doesn't start with "Manim", so maybe rather `Manim Interactive`? Or `Manim Interact`. It'd be funny to call it `Checkpoint Paste` but then no one finds it...

**Comment by bhoov** [comment]
I agree that it would be nice to start with "manim". Your suggestions make me wonder -- how about "Manim Notebook"? For the target audience, the term "notebook" should elicit and interaction style similar to Jupyter, which is the aim of the extension.

**Comment by Splines** [comment]
Oh yeah, `Manim Notebook` sounds great 👍.

Just have to add that it might turn users off because they think it's like a Jupyter Notebook experience (at least for me, it's a love-hate relationship since it's really neat, but then I also hate that variables spill over everywhere and makes debugging a nightmare).

But that expectancy management could be tackled by a good feature description in the Readme.

**Comment by bhoov** [comment]
Sounds good! For the next release we'll rebrand to "Manim Notebook" and buff up the Readme for users who explicitly DON'T want to work in a jupyter notebook setting.
