### ISSUE TITLE
Show progress in VSCode

### ISSUE THREAD

**Issue by Splines** [bhoov/manim-notebook#14]
I came across the [Progress API](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#progress-api) to show progress like in [this sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/progress-sample):

![preview](https://github.com/user-attachments/assets/0b1ac9e8-bb40-44ee-9973-0e582347f84b)

Then I had the following idea:
- When sending the command to Manim, get back the terminal stdout stream where Manim outputs its progress
- Process that string a bit to make it nicely readable inside a popup
- Show the continuous progress as running notification

In the long-term: why do users even have to interact with the Terminal to see Manim output? The only contact point is if you want to run your own quick commands in the interactive shell. But honestly, I'd rather just create a new Manim Cell and preview that one as it's more comfortable to program in the editor instead of a terminal. I'm not demanding to take away the possibility to have the terminal opened. But this could be opt-in for "advanced" users while keeping others in VSCode itself. They could click on "Preview Manim Cell" and see the progress directly as discussed here.

The tricky part is getting the stream of a terminal. I've experimented a bit with the new Terminal API and didn't get it to work (but I didn't also try for too long). If you want to try it, [this is a good StackOverflow answer](https://stackoverflow.com/a/77456264/9655481).

**Comment by Splines** [comment]
I got it to work now and can read the output from the Terminal, at least when it's newly spun up (not for an existing running terminal). I also developed a first prototype which shows the progress of the Manim scene. Will tackle this new feature on the side.

**Comment by bhoov** [comment]
I love the idea of this to slowly remove dependence on a visible ipython terminal, but i think we can wait on this feature for after v0.1.0
