### ISSUE TITLE
Support shortcut for starting `manimgl` interactively based on current line

### ISSUE THREAD

**Issue by Splines** [bhoov/manim-notebook#2]
Such a command (with an assignable shortcut) could do the following

### Steps
- Launch a new terminal in a floating window
- Execute `manimgl` with params based on the which line the cursor is in, that is
    - Find out in which file the cursor is (probably easy), e.g. `path/to/file.py` based on the current directory where VSCode is open
    - Find out in which python class the cursor is (probably a lot trickier, maybe `pylance` provides kind of an API for this?), e.g. `SceneName`
    - Find out the current line number (probably easy), e.g. `42`
    - Pass everything as `mangiml path/to/file.py SceneName -se 42`

### **Additional**
- Before doing all of this, check if there isn't already a terminal open. If there is none open, do the steps above.
- If there is already a terminal open: somehow check if `manimgl` was already launched in interactive mode (in any of the open terminals).
   - If yes: is there a way to restart it on a new line number? For this case, it is maybe easier to just kill the active session and open a new one. However, this would have the disadvantage that the window position of the OpenGL popup is lost.
   - If no: just start it as described above.
   - Special case: what if multiple terminals run `manimgl`? Should probably report an error in this case.

**Comment by VladimirFokow** [comment]
implemented [here](https://github.com/VladimirFokow/vscode-manim/blob/add_command_run_scene/src/extension.ts#L33-L122)

**Comment by bhoov** [comment]
Argh, I would really like to have this functionality as part of the extension before I publish this extension's awesome recent developments (thanks you both!) to the marketplace. However, after doing some research the CC-BY-NC-SA license is not compatible with the MIT license I am currently using. We have two options:

1. We can implement our own logic from scratch, without inspiration from the original implementation. Or,
2. We can update the extension's license to CC-BY-NC-SA 

I believe this is a very important feature to have as part of the extension. Let me know your thoughts

**Comment by VladimirFokow** [comment]
Hi!
Really awesome contributions from @Splines !

I believe Grand [has allowed](https://github.com/3b1b/videos/issues/79#issuecomment-2417372590) to use the workflow itself without the CC license.

**Comment by VladimirFokow** [comment]
Yes, I'll do that in 1 h

**Comment by bhoov** [comment]
This was closed by #17
