### ISSUE TITLE
Use already open Manim interactive shell

### ISSUE THREAD

**Issue by Splines** [bhoov/manim-notebook#24]
If there is any terminal already opened that has Manim running in IPython, we should use that terminal. With this detection logic, we could also error if users use the `Quit Preview` command when they don't have any Manim session open. Other commands could also profit from this behavior.

If multiple Manim scenes are opened, e.g. two terminals with running IPython Manim session, then use the terminal that is visible to the user. If both are visible, use the one that has the current focus. If none has the current focus, use the one that had the focus the most recently.

Also see [this comment](https://github.com/bhoov/manim-notebook/pull/17#issuecomment-2430409771) and the last section of my comment [here](https://github.com/bhoov/manim-notebook/issues/2#issue-2589908135).

**Comment by VladimirFokow** [comment]
with this detecting logic - we can also have a HUGE usability improvement:

new users will just need to click "Preview Manim Cell" -> 
we add detection, and if their manimgl isn't running - we start it at the start of the scene, 
and only then run the cell

**Comment by bhoov** [comment]
This would be an awesome feature, I agree about the usability improvement. I'm going through and labeling features for a v0.1.0 release. My goal is to have it on the marketplace by end of the weekend so we can announce on twitter/where you all like early next week. Do you all think this is a priority to integrate for v0.1.0?

**Comment by VladimirFokow** [comment]
Of course, it would be great to implement it;

but there are still a couple of bug-issues - do you want to announce with them unresolved?

**Comment by Splines** [comment]
See also my comment [here](https://github.com/bhoov/manim-notebook/issues/16#issuecomment-2437006262) for an idea about `ManimShell`.
