### ISSUE TITLE
Start scene should warn before killing active session

### ISSUE THREAD

**Issue by bhoov** [bhoov/manim-notebook#36]
(see [this comment](https://github.com/bhoov/manim-notebook/pull/30#issuecomment-2439781301))

> Re: If the start scene command is invoked while a preview is already running, close the current session and invoke a new one -- I find this a bit jarring that we automatically kill, even if the hotkey is accidentally pressed. From a user-experience perspective, I would prefer a pop-up question "Would you like to kill the existing manim shell to start a new shell at the cursor? [y/N]"

Right now, a user can run the "Start scene at cursor" command which will automatically kill the existing terminal and start a new session at the specified line. It will benefit new users who are learning the commands and hotkeys to warn if we are killing their session

**Comment by Splines** [comment]
[Notifications with actions example code](https://github.com/microsoft/vscode-extension-samples/blob/2ac108b6521214202e5d42a7f74576652a8b4e37/notifications-sample/src/extension.ts#L23C2-L30C5) | [UX guidelines](https://code.visualstudio.com/api/ux-guidelines/notifications#notification-examples)
