### ISSUE TITLE
some "Preview Manim Cell" execute but progress bar hangs (MacOS)

### ISSUE THREAD

**Issue by VladimirFokow** [bhoov/manim-notebook#52]
Example:

```py
from manimlib import *

 
class SquareToCircle(Scene):
    def construct(self):
        # 
        ## Set up
        circle = Circle()
        circle.set_fill(BLUE, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)
        square = Square()

        ## Cell
        self.play(ShowCreation(square), run_time=3)
        self.play(ReplacementTransform(square, circle))
        self.wait()

```

- start scene on line 17

- click "Preview Manim Cell" on line 7

Hangs:

![Screenshot 2024-10-28 at 22 28 13](https://github.com/user-attachments/assets/b224e5ab-c454-44e2-9dac-afe01e01784c)

<br /><br />

It doesn't matter where you _start_ the scene. 

The problem is:
"Preview Manim Cell" just always hangs.. - for the First cell only.
(2nd cell works!!)

What solved it: pressing "Enter" in the terminal.

<br /><br />

Hypothesis of what could be the reason:

- Cell 1 doesn't output any progress bars to the terminal
- but cell 2 does

is execution triggered by progress bars?

<br /><br />

@Splines reproducible on linux?

**Comment by Splines** [comment]
Mmh, ok that's weird, for me it works just fine even for the first scene.

https://github.com/user-attachments/assets/8ada6b3b-5c41-4457-82ba-ae6b7df7852a


You know what: this is now a good time to introduce some logging to the extension (not just debugging console, but a proper file). This way, for future issues, we can ask users to send us the log, otherwise issues like these are really hard to debug as I don't have any MacOS system.

**Comment by bhoov** [comment]
I can confirm with @VladimirFokow the hanging on MacOS. Must fix. Good find!

**Comment by VladimirFokow** [comment]
Update:


looks like the commands DO execute,
BUT just:
the "Previewing Manim" info box doesn't go away until the user presses Enter

**Comment by VladimirFokow** [comment]
Update:

With the new logging system, here is the fresh log file.

[Manim Notebook.log](https://github.com/user-attachments/files/17579712/Manim.Notebook.log)


```py
from manimlib import *
import time

class SquareToCircle(Scene):
    def construct(self):
        #
        ## Test
        print('1')
        # time.sleep(1)
        print('2')
```


- start manim on line 6
- open the manim terminal
- start logging
- "run manim cell" -> it runs, but then hangs
- wait a bit
- click Enter in the terminal -> it stops hanging

**Comment by VladimirFokow** [comment]
Log file 2: [Manim Notebook.log](https://github.com/user-attachments/files/17579757/Manim.Notebook.log)

Same code as above.

New steps:

- start manim on line 6
- start logging
- click "preview manim cell" -> it runs, but then hangs
- open the manim terminal -> IT STOPS HANGING (just because of opening the terminal)
- select code, run it -> it hangs
- press Enter -> it stops hanging

**Comment by VladimirFokow** [comment]
## Log 3: 
[Manim Notebook.log](https://github.com/user-attachments/files/17579801/Manim.Notebook.log)

To show that: sleep causes it to stop hanging.
Also: to show an example how it stops hanging.

Code: same as above with uncommented sleep:

```py
from manimlib import *
import time

class SquareToCircle(Scene):
    def construct(self):
        #
        ## Test
        print('1')
        time.sleep(1)
        print('2')
```

Steps:

- start logging
- click "preview manim cell" -> 1 sec progress bar, then progress bar ends like it should
- click "preview manim cell" -> 1 sec progress bar, then progress bar ends like it should

**Comment by VladimirFokow** [comment]
# Log 4:

[Manim Notebook.log](https://github.com/user-attachments/files/17579866/Manim.Notebook.log)

To show that:

- if I type something in the manim terminal, it doesn't hange then

**Comment by VladimirFokow** [comment]
hm.. considering this looks very weird,
@Splines I certainly don't expect you to solve this without even having a MacOS system.

I would be able to see how your Shell class works in the coming 1-2 months, and debug it from the ground up
