### ISSUE TITLE
Cannot run Manim commands when it's started 2nd time (MacOS)

### ISSUE THREAD

**Issue by VladimirFokow** [bhoov/manim-notebook#53]
On macOS, after starting Manim and then quitting it - it doesn't run again.

<br />

For example:

- start a Manim window (with any method)
- finish it (with any method)

<br />

After that - problems:

- "Preview Manim Cell" - 
doesn't work, raises a notification:

  > Simultaneous Manim commands are not currently
supported on MacOS. Please wait for the current
operations to finish before initiating a new command.

- "Preview selection" command -
 doesn't work, same notification.

- start `manimgl` via a terminal - works (it starts). 
 But then the "Preview Manim Cell" , "Preview selection" commands continue NOT working - having the same behavior..

**Comment by bhoov** [comment]
I can confirm this bug. Another important fix before release...

@VladimirFokow we should probably dive into the `ManimShell.ts` code to help @Splines with this implementation. He doesn't have a way to debug things on his end. It's actually quite frustrating these diff behaviors between WSL and MacOS -- I thought Electron was supposed to solve these issues 😂 lol

I suggest tackling some of the MacOS facing integration tests suggested in #47 as we try to resolve these OS conflicts. This is my first extension in VS Code, and it will also be my first attempt at testing in TS 🙈, but it will be very valuable. We can keep the tests local for now (i.e., running the suite on @Splines windows machines and our MacOS machines) and figure out how to integrate a CI pipeline later

**Comment by VladimirFokow** [comment]
Log file:

[Manim Notebook.log](https://github.com/user-attachments/files/17579536/Manim.Notebook.log)



Here's what I did:

```py
from manimlib import *
import time

class SquareToCircle(Scene):
    def construct(self):
        #
        ## Test
        circle = Circle()
        self.play(ShowCreation(circle))
```


- reload window
- start logging (trace level)
- click "run manim cell"
- command: "quit preview"
- click "run manim cell" -> broken
- start manim on line 6
- click "run manim cell" -> broken

**Comment by Splines** [comment]
>  It's actually quite frustrating these diff behaviors between WSL and MacOS -- I thought Electron was supposed to solve these issues 😂 lol

@bhoov Yes, these differences are frustrating. But I'm not sure it's Electron's fault. We're dealing with a terminal and I suspect that communicating with underlying layers might reveal more difference shere than in other areas where "just" a regular Chromium browser is used and that is abstracted away in higher layers than the "bare-bone" terminal.

---

> Here's what I did:

@VladimirFokow  Thank you very much for the logfile and the enumeration of steps you've performed, this will hopefully make it possible for me to fix the issue in the following days.
