### ISSUE TITLE
Cancel mid-execution: Ctrl+C (MacOS)

### ISSUE THREAD

**Issue by VladimirFokow** [bhoov/manim-notebook#54]
This issue is to track: https://github.com/3b1b/manim/discussions/2236

if a solution there is ready - do this: https://github.com/bhoov/manim-notebook/issues/16#issuecomment-2439741160

**Comment by bhoov** [comment]
@VladimirFokow should the title say `Ctrl+C`?

**Comment by VladimirFokow** [comment]
please feel free to change how you see fit

**Comment by bhoov** [comment]
(I unfortunately cannot modify the title of the issue in the other repo 😬)

**Comment by VladimirFokow** [comment]
in the other repo?
This is your repo

**Comment by bhoov** [comment]
Sorry for the confusion. In the [3b1b/manim issue](https://github.com/3b1b/manim/discussions/2236) you linked to in [this comment](https://github.com/bhoov/manim-notebook/issues/54#issue-2619760367). When I open it, I see that the title is 

<img width="849" alt="image" src="https://github.com/user-attachments/assets/e1fe4993-ad8b-4b7b-8e7c-47ad20c1434f">

> Why does IPhython quit on Cmd+C (MacOS)?

**Comment by VladimirFokow** [comment]
ah, thanks!! changed that

**Comment by VladimirFokow** [comment]
closing for now. Reopen when there are new developments
