### ISSUE TITLE
[bug] log file not cleared on reload-window (MacOS)

### ISSUE THREAD

**Issue by VladimirFokow** [bhoov/manim-notebook#58]
See 5 messages here:

https://github.com/bhoov/manim-notebook/pull/57#issuecomment-2444095357

> Is the old log file ever cleared?
> I just reloaded the window,
opened the log file,
but all my old logs are still there..
> (I thought the README says to reload the window - in order for the old logs to be removed?)

**Comment by Splines** [comment]
wanted behavior is described in [this video](https://github.com/bhoov/manim-notebook/pull/57#issuecomment-2444404029)

**Comment by Splines** [comment]
@VladimirFokow I've opened an issue for this in the vscode repo [here](https://github.com/microsoft/vscode/issues/232500). Feel free to subscribe to it should they have MacOS-specific questions.

**Comment by VladimirFokow** [comment]
To make this issue ready for v0.1.0 NOW:

- describe in the [Troubleshooting section](https://github.com/bhoov/manim-notebook?tab=readme-ov-file#troubleshooting): 
 If you're on MacOS: first use manim command to open the log file,
  then delete everything from it,
  then reload window (reloading the window will log to this file your system info),
   (then - the rest of the steps)

- move the [Troubleshooting section](https://github.com/bhoov/manim-notebook?tab=readme-ov-file#troubleshooting) into the GitHub wiki 
  (because: we don't want to put these distracting details on the main page of the extension which all first-time users see)
  (just can add a link to it in the "Links" section of the README)



Afterwards, whenever the technical limitations are solved by the VSCode maintainers,
our workflow can be improved accordingly.

But we don't need to wait for them now - to make this extension usable comfortably.

**Comment by VladimirFokow** [comment]
The new way is awesome!
This issue will be closed by it
