### ISSUE TITLE
TODO: camera motions

### ISSUE THREAD

**Issue by VladimirFokow** [bhoov/manim-notebook#6]
- shortcut to get current camera angle
   and paste it

how is it done on the video?

<br />

(I propose the shortcut `cmd+' cmd+v`)

**Comment by Splines** [comment]
This is [here](https://youtu.be/rbu7Zu5X1zI?t=2054) in the video _How I animate 3Blue1Brown_. The code to copy the current camera position to the clipboard is found [here](https://github.com/3b1b/manim/blob/d499544366570b67a070dcfcb303f31ce4483712/manimlib/scene/interactive_scene.py#L620-L635).

**Comment by bhoov** [comment]
> both times the "animation" window is focused when the shortcut is clicked.
> 
> I don't know how one would create such a shortcut.

@VladimirFokow looks like his shortcuts are defined in the manim library and not through a sublime plugin. See [this line](https://github.com/3b1b/manim/blob/1139b545f9e766e7282f8cf64e68e225a4f25eb1/manimlib/scene/interactive_scene.py#L508) in the `InteractiveScene`.

**Comment by VladimirFokow** [comment]
ooooh, nice! 
Then it already works!

`shift+d`

We can close this issue
