### ISSUE TITLE
Add command "Clear scene cache"

### ISSUE THREAD

**Issue by bhoov** [bhoov/manim-notebook#63]
If cells are run out of order, the manim caching system that makes interactive development so nice starts to hurts us -- the scene's state at the beginning of a cell will be incorrect, even if we run the cells from the beginning 

Current hacky solutions:
1. Rename the title of this cell and all preceding cells to be different to ignore the caching mechanism, then rerun cells from the beginning
2. Restart the manim session

Honestly, option 2 is more robust. If ever cells are run out of order, it is currently easiest just to restart the session.

**Comment by VladimirFokow** [comment]
But can we just do this?:

1. run command: `manim notebook: clear`

2. then select everything until the scene start, and run command: manim notebook: execute selection

**Comment by VladimirFokow** [comment]
Isn't the current simpler solution just to:

- restart the scene?

**Comment by bhoov** [comment]
> ah... do you mean: the first cell has a comment,
> and this comment returns the cell to its state when you first ran it, even though that state wasn't blank?

Yes this is what I mean. It seems that `restarting the scene` is the only solution we currently have if cells are run out of order. 

Clearing the cache is not the correct way to solve this usability quirk. I cannot think of a better solution than restarting the scene. I will close this issue.
