### ISSUE TITLE
Enable ManimCE

### ISSUE THREAD

**Issue by x18-1** [bhoov/manim-notebook#68]
Hope enable ManimCE

**Comment by VladimirFokow** [comment]
Relevant discussion:
https://github.com/ManimCommunity/manim/discussions/3954


for that I think we need them to implement the `checkpoint_paste()` functionality

**Comment by Splines** [comment]
This is probably not something that is going to happen any time soon as the ManimCE version (as far as I know) doesn't currently support OpenGL which 3Blue1Brown's `manimgl` relies on to show the interactive preview. As behackl stated [in this comment](https://github.com/ManimCommunity/manim/discussions/3954#discussioncomment-10933882):

> It mainly is a question of resources; we have been working on a refactor of the render loop for ages, recently with some more progress on our experimental branch. But progress is slow, and people get busy with other things. Help to get things done is, of course, always welcome.

Instead for ManimCE, you might want to explore the concepts of [`Section`](https://docs.manim.community/en/stable/reference/manim.scene.section.Section.html#section)s. Also see [here](https://docs.manim.community/en/stable/tutorials/output_and_config.html#sections) in the tutorials.

---

Until then, this extension will focus on working with `manimgl` and there are currently no plans to support the community edition (at least I don't have plans to do so in the near future). Instead, we focus on improving the user experience for interactively previewing Manim code from `manimgl` as this example shows:

https://github.com/user-attachments/assets/13086817-229a-4151-9642-63fc91146f43

Feel free to reopen the issue in the future once ManimCE supports some kind of previewing built-in (maybe as well with an OpenGL renderer). In the best case, they provide a command similar to `manimgl` that we can just swap out in this extension to support ManimCE as well.
